// Generated by CoffeeScript 1.6.3
(function() {
  App.CalendarView = Parse.View.extend({
    className: 'row-fluid calendar-wrapper',
    template: $.template('content-calendar'),
    initialize: function() {},
    render: function() {
      var d, date, m, options, y;
      this.$el.html(this.template({}));
      date = new Date();
      d = date.getDate();
      m = date.getMonth();
      y = date.getFullYear();
      this.calendar = this.$('.calendar');
      this.fullCalendar = this.calendar.fullCalendar.bind(this.calendar);
      options = {
        header: {
          left: 'month,agendaWeek,agendaDay',
          center: 'title',
          right: 'today prev,next'
        },
        selectable: true,
        selectHelper: true,
        editable: true,
        events: [
          {
            title: 'All Day Event',
            start: new Date(y, m, 1)
          }, {
            title: 'Long Event',
            start: new Date(y, m, d - 5),
            end: new Date(y, m, d - 2)
          }, {
            id: 999,
            title: 'Repeating Event',
            start: new Date(y, m, d - 3, 16, 0),
            allDay: false
          }, {
            title: 'Lunch',
            start: new Date(y, m, d, 12, 0),
            end: new Date(y, m, d, 14, 0),
            allDay: false
          }, {
            title: 'Click for Google',
            start: new Date(y, m, 28),
            end: new Date(y, m, 29),
            url: 'http://google.com/'
          }
        ],
        eventBackgroundColor: '#278ccf'
      };
      this.fullCalendar(options);
      return this;
    },
    events: {
      'click .popup .close-pop': 'closeEvent'
    },
    closeEvent: function(event) {
      return $(event.target).parent('.new-event').fadeOut('fast');
    }
  });

}).call(this);

/*
//@ sourceMappingURL=calendar.map
*/
