// Generated by CoffeeScript 1.6.3
(function() {
  App.SideBar = Parse.View.extend({
    el: $('#dashboard-menu'),
    initialize: function() {
      this.arrow = $('<div>', {
        "class": 'pointer'
      }).append($('<div>', {
        "class": 'arrow'
      }), $('<div>', {
        "class": 'arrow_border'
      }));
      return this.render();
    },
    template: $.template('sidebar-menu'),
    render: function() {
      return this.$el.html(this.template({}));
    },
    events: {
      'click .dropdown-toggle': 'toggleSubmenu'
    },
    toggleSubmenu: function(event) {
      var submenu, toggle;
      event.preventDefault();
      toggle = $(event.currentTarget);
      submenu = toggle.next('ul.submenu');
      if (toggle.hasClass('active')) {
        toggle.removeClass('active');
        return submenu.slideUp('fast');
      } else {
        toggle.addClass('active');
        return submenu.slideDown('fast');
      }
    },
    update: function() {
      var activeTab, fragment,
        _this = this;
      fragment = Parse.history.fragment;
      activeTab = (function() {
        switch (false) {
          case !fragment.match(/^calendar/):
            return 1;
          case fragment !== 'analytics':
            return 2;
          case !fragment.match(/^users/):
            return 3;
          default:
            return 0;
        }
      })();
      return this.$('> li').each(function(index, li) {
        if (index === activeTab) {
          return $(li).addClass('active', {
            duration: 200
          }).prepend(_this.arrow.detach());
        } else {
          return $(li).removeClass('active', {
            duration: 200
          });
        }
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=sidebar.map
*/
