// Generated by CoffeeScript 1.6.3
(function() {
  var app, conn, express, http, port, server;

  http = require("http");

  express = require("express");

  conn = require("./connections");

  app = express();

  server = http.createServer(app);

  conn.start(server);

  conn.asocket(/rebuildDB/, function(ws) {
    ws.send("rebuilding DB...");
    console.log("rebuilding DB...");
    return gamescripts.buildDB(function(err, gameId) {
      ws.send("added game " + gameId);
      return console.log("added game " + gameId);
    });
  });

  app.get('/version', function(req, resp) {
    return readJson('package.json', function(err, _arg) {
      var version;
      version = _arg.version;
      resp.writeHead(200, {
        "Content-Type": "application/json"
      });
      resp.write(JSON.stringify({
        version: version
      }));
      return resp.end();
    });
  });

  port = process.env.PORT || 3000;

  server.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
